set(zlib_INCLUDE_DIRS $ENV{REZ_ZLIB_ROOT}/include)
set(zlib_LIBRARY_DIRS $ENV{REZ_ZLIB_ROOT}/lib)
if(zlib_STATIC)
	set(zlib_LIBRARIES ${zlib_LIBRARY_DIRS}/libz.a)
else()
	set(zlib_LIBRARIES ${zlib_LIBRARY_DIRS}/libz.so)
endif()